[common]
level = "local"
serviceName = "abcfe-node"
port = 10000
mode = "boot"
networkID = "abcfe-mainnet"
blockProducer = true

[logInfo]
path = "./log/syslogs/"
maxAgeHour = 1440
rotateHour = 24
ProdTelKey = ""
ProdChatId = 0
DevTelKey = ""
DevChatId = 0

[db]
path = "./resource/db/"

[wallet]
path = "./resource/wallet"

[version]
protocol = "1.0.0"
transaction = "1.0.0"

[genesis]
SystemAddresses = ["90efb3f6337ff1cc31398426ef62e4f48d9d73e6"]
SystemBalances = [500000000]
Timestamp = 1767253675

[server]
RestPort = 8000
InternalRestPort = 8800

[p2p]
Address = "0.0.0.0"
Port = 30303
BootNodes = []

[fee]
minFee = 1
blockReward = 50

[transaction]
maxMemoSize = 256
maxDataSize = 1024

[consensus]
proposerSelection = "roundrobin"

[validators]
list = [
  { address = "90efb3f6337ff1cc31398426ef62e4f48d9d73e6", publicKey = "3059301306072a8648ce3d020106082a8648ce3d03010703420004d587948801cbeed5b753cd999e9e09cf06c624acb2c9e93d8645daaf3a3ce00a4aa2933b12728a6b13e85f6a21ac42c189812d26b72193ae6caa9787d9b6a0e4", votingPower = 1000 }
]
