[common]
level = "local"
serviceName = "abcfe-node"
port = 10000
mode = "boot"
networkID = "abcfe-mainnet"
blockProducer = true

[logInfo]
path = "./log/syslogs/"
maxAgeHour = 1440
rotateHour = 24
ProdTelKey = "https://api.telegram.org/bot7680194780:AAH8x_GSIdSlQIBcffSBPkxRvTr63ssrrbE/sendMessage"
ProdChatId = -4572666133
DevTelKey = "https://api.telegram.org/bot7821171888:AAH9oi3bI7M-rGZJvRM2J5h6vYXJ3KxqKf0/sendMessage"
DevChatId = -4572666133

[db]
path = "./resource/db/"

[wallet]
path = "./resource/wallet"

[version]
protocol = "1.0.0"
transaction = "1.0.0"

[genesis]
SystemAddresses = ["d79d745230218fc50118c59b0ee2c73934768a5f"]
SystemBalances = [500000000]

[server]
RestPort = 8000

[p2p]
Address = "0.0.0.0"
Port = 30303
BootNodes = []

[fee]
minFee = 1000           # 최소 수수료 (1000 단위)
blockReward = 50000000  # 블록 생성 보상 (50 토큰)
